package fr.jukien.intellij.plugins.ui;

import javax.swing.*;

/**
 * Created on 24/04/2019
 *
 * @author JDI
 * @version 2.0.0
 * @since 1.0.0
 */
public class POJOGeneratorPanel {
    private JPanel panel;
    private JCheckBox capitalizeTheNameOfCheckBox;
    private JCheckBox addGeneratedValueAnnotationsForAutoIncrementalSequences;

    public POJOGeneratorPanel(POJOGeneratorSettings pojoGeneratorSettings) {
        // Initialise l'interface graphique avec les settings qui ont été enregistrés avant
        capitalizeTheNameOfCheckBox.setSelected(pojoGeneratorSettings.getCapitalize());
        addGeneratedValueAnnotationsForAutoIncrementalSequences.setSelected(pojoGeneratorSettings.getAutoGenerated());
    }

    public JPanel getPanel() {
        return panel;
    }

    public JCheckBox getCapitalizeTheNameOfCheckBox() {
        return capitalizeTheNameOfCheckBox;
    }

    public JCheckBox getAddGeneratedValueAnnotationsForAutoIncrementalSequences() {
        return addGeneratedValueAnnotationsForAutoIncrementalSequences;
    }
}
