package fr.jukien.intellij.plugins.ui;

import javax.swing.*;

/**
 * Created on 24/04/2019
 *
 * @author JDI
 * @version 2.0.0
 * @since 1.0.0
 */
public class POJOGeneratorPanel {
    private JPanel panel;
    private JCheckBox capitalizeCheckBox;
    private JCheckBox generatedValueAnnotationsCheckBox;
    private JCheckBox manyToOneAndJoinColumnAnnotationsCheckBox;

    public POJOGeneratorPanel(POJOGeneratorSettings pojoGeneratorSettings) {
        // Initialise l'interface graphique avec les settings qui ont été enregistrés avant
        capitalizeCheckBox.setSelected(pojoGeneratorSettings.getCapitalize());
        generatedValueAnnotationsCheckBox.setSelected(pojoGeneratorSettings.getAutoGenerated());
        manyToOneAndJoinColumnAnnotationsCheckBox.setSelected(pojoGeneratorSettings.getWithRelationshipAnnotations());
    }

    public JPanel getPanel() {
        return panel;
    }

    public JCheckBox getCapitalizeCheckBox() {
        return capitalizeCheckBox;
    }

    public JCheckBox getGeneratedValueAnnotationsCheckBox() {
        return generatedValueAnnotationsCheckBox;
    }

    public JCheckBox getManyToOneAndJoinColumnAnnotationsCheckBox() {
        return manyToOneAndJoinColumnAnnotationsCheckBox;
    }
}
