package fr.jukien.intellij.plugins.ui;

import com.intellij.openapi.components.PersistentStateComponent;
import com.intellij.openapi.components.State;
import com.intellij.openapi.components.Storage;
import com.intellij.util.xmlb.XmlSerializerUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Created on 25/04/2019
 *
 * @author JDI
 * @version 2.3.0
 * @since 1.0.0
 */
@State(
        name = "POJOGeneratorSettings",
        storages = {
                @Storage("POJOGeneratorSettings.xml")}
)
public class POJOGeneratorSettings implements PersistentStateComponent<POJOGeneratorSettings> {
    private Boolean capitalize;
    private Boolean withSchemaAttribute;
    private Boolean autoGenerated;
    private Boolean withRelationshipAnnotations;
    private Boolean generateCompositePrimaryKey;
    private Boolean generateCompositePrimaryKeyWithIdClassAnnotation;
    private Boolean generateCompositePrimaryKeyWithEmbeddedIdAnnotation;
    private String dtoFolderPath;
    private String entityFolderPath;
    private String prefixCompositePrimaryKey;
    private String suffixCompositePrimaryKey;
    private String prefixEntity;
    private String suffixEntity;
    private String prefixDto;
    private String suffixDto;
    private Boolean alwaysShowDifferencesBetweenFiles;

    public POJOGeneratorSettings() {
        capitalize = false;
        autoGenerated = false;
        withSchemaAttribute = false;
        withRelationshipAnnotations = false;
        generateCompositePrimaryKey = false;
        generateCompositePrimaryKeyWithIdClassAnnotation = true;
        generateCompositePrimaryKeyWithEmbeddedIdAnnotation = false;
        prefixCompositePrimaryKey = "";
        suffixCompositePrimaryKey = "Id";
        prefixEntity = "";
        suffixEntity = "";
        prefixDto = "";
        suffixDto = "DTO";
        alwaysShowDifferencesBetweenFiles = false;
    }

    @Nullable
    @Override
    public POJOGeneratorSettings getState() {
        return this;
    }

    @Override
    public void loadState(@NotNull POJOGeneratorSettings state) {
        XmlSerializerUtil.copyBean(state, this);
    }

    public Boolean getCapitalize() {
        return capitalize;
    }

    public void setCapitalize(Boolean capitalize) {
        this.capitalize = capitalize;
    }

    public Boolean getWithSchemaAttribute() {
        return withSchemaAttribute;
    }

    public void setWithSchemaAttribute(Boolean withSchemaAttribute) {
        this.withSchemaAttribute = withSchemaAttribute;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Boolean getWithRelationshipAnnotations() {
        return withRelationshipAnnotations;
    }

    public void setWithRelationshipAnnotations(Boolean withRelationshipAnnotations) {
        this.withRelationshipAnnotations = withRelationshipAnnotations;
    }

    public Boolean getGenerateCompositePrimaryKey() {
        return generateCompositePrimaryKey;
    }

    public void setGenerateCompositePrimaryKey(Boolean generateCompositePrimaryKey) {
        this.generateCompositePrimaryKey = generateCompositePrimaryKey;
    }

    public Boolean getGenerateCompositePrimaryKeyWithIdClassAnnotation() {
        return generateCompositePrimaryKeyWithIdClassAnnotation;
    }

    public void setGenerateCompositePrimaryKeyWithIdClassAnnotation(Boolean generateCompositePrimaryKeyWithIdClassAnnotation) {
        this.generateCompositePrimaryKeyWithIdClassAnnotation = generateCompositePrimaryKeyWithIdClassAnnotation;
    }

    public Boolean getGenerateCompositePrimaryKeyWithEmbeddedIdAnnotation() {
        return generateCompositePrimaryKeyWithEmbeddedIdAnnotation;
    }

    public void setGenerateCompositePrimaryKeyWithEmbeddedIdAnnotation(Boolean generateCompositePrimaryKeyWithEmbeddedIdAnnotation) {
        this.generateCompositePrimaryKeyWithEmbeddedIdAnnotation = generateCompositePrimaryKeyWithEmbeddedIdAnnotation;
    }

    public String getDtoFolderPath() {
        return dtoFolderPath;
    }

    public void setDtoFolderPath(String dtoFolderPath) {
        this.dtoFolderPath = dtoFolderPath;
    }

    public String getEntityFolderPath() {
        return entityFolderPath;
    }

    public void setEntityFolderPath(String entityFolderPath) {
        this.entityFolderPath = entityFolderPath;
    }

    public String getPrefixCompositePrimaryKey() {
        return prefixCompositePrimaryKey;
    }

    public void setPrefixCompositePrimaryKey(String prefixCompositePrimaryKey) {
        this.prefixCompositePrimaryKey = prefixCompositePrimaryKey;
    }

    public String getSuffixCompositePrimaryKey() {
        return suffixCompositePrimaryKey;
    }

    public void setSuffixCompositePrimaryKey(String suffixCompositePrimaryKey) {
        this.suffixCompositePrimaryKey = suffixCompositePrimaryKey;
    }

    public String getPrefixEntity() {
        return prefixEntity;
    }

    public void setPrefixEntity(String prefixEntity) {
        this.prefixEntity = prefixEntity;
    }

    public String getSuffixEntity() {
        return suffixEntity;
    }

    public void setSuffixEntity(String suffixEntity) {
        this.suffixEntity = suffixEntity;
    }

    public String getPrefixDto() {
        return prefixDto;
    }

    public void setPrefixDto(String prefixDto) {
        this.prefixDto = prefixDto;
    }

    public String getSuffixDto() {
        return suffixDto;
    }

    public void setSuffixDto(String suffixDto) {
        this.suffixDto = suffixDto;
    }

    public Boolean getAlwaysShowDifferencesBetweenFiles() {
        return alwaysShowDifferencesBetweenFiles;
    }

    public void setAlwaysShowDifferencesBetweenFiles(Boolean alwaysShowDifferencesBetweenFiles) {
        this.alwaysShowDifferencesBetweenFiles = alwaysShowDifferencesBetweenFiles;
    }
}
