package fr.jukien.intellij.plugins.util;

import com.intellij.database.model.DataType;

/**
 * Created on 24/04/2019
 *
 * @author JDI
 * @version 1.1.0
 * @since 1.0.0
 */
public class Field {
    private String name;
    private Boolean isAutoGenerated;
    private Boolean isPrimary;
    private Boolean isForeignKey;
    private DataType SQLType;
    private String javaType;
    private String columnDefinition;

    public Field() {
        this.isAutoGenerated = false;
        this.isPrimary = false;
        this.isForeignKey = false;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public Boolean getPrimary() {
        return isPrimary;
    }

    public void setPrimary(Boolean primary) {
        isPrimary = primary;
    }

    public Boolean getForeignKey() {
        return isForeignKey;
    }

    public void setForeignKey(Boolean foreignKey) {
        isForeignKey = foreignKey;
    }

    public DataType getSQLType() {
        return SQLType;
    }

    public void setSQLType(DataType SQLType) {
        this.SQLType = SQLType;
    }

    public String getJavaType() {
        return javaType;
    }

    public void setJavaType(String javaType) {
        this.javaType = javaType;
    }

    public String getColumnDefinition() {
        return columnDefinition;
    }

    public void setColumnDefinition(String columnDefinition) {
        this.columnDefinition = columnDefinition;
    }
}
